codon_table_v2 = {
    "GCT": "A_Alanine",
    "GCC": "A_Alanine",
    "GCA": "A_Alanine",
    "GCG": "A_Alanine",
    "CGT": "R_Arginine",
    "CGC": "R_Arginine",
    "CGA": "R_Arginine",
    "CGG": "R_Arginine",
    "AGA": "R_Arginine",
    "AGG": "R_Arginine",
    "AAT": "N_Asparagine",
    "AAC": "N_Asparagine",
    "GAT": "D_Asparticacid",
    "GAC": "D_Asparticacid",
    "TGT": "C_Cysteine",
    "TGC": "C_Cysteine",
    "CAA": "Q_Glutamine",
    "CAG": "Q_Glutamine",
    "GAA": "E_Glutamicacid",
    "GAG": "E_Glutamicacid",
    "GGT": "G_Glycine",
    "GGC": "G_Glycine",
    "GGA": "G_Glycine",
    "GGG": "G_Glycine",
    "CAT": "H_Histidine",
    "CAC": "H_Histidine",
    "ATT": "I_Isoleucine",
    "ATC": "I_Isoleucine",
    "ATA": "I_Isoleucine",
    "TTA": "L_Leucine",
    "TTG": "L_Leucine",
    "CTT": "L_Leucine",
    "CTC": "L_Leucine",
    "CTA": "L_Leucine",
    "CTG": "L_Leucine",
    "AAA": "K_Lysine",
    "AAG": "K_Lysine",
    "ATG": "開始コドン",
    "TTT": "F_Phenylalanine",
    "TTC": "F_Phenylalanine",
    "CCT": "P_Proline",
    "CCC": "P_Proline",
    "CCA": "P_Proline",
    "CCG": "P_Proline",
    "TCT": "S_Serine",
    "TCC": "S_Serine",
    "TCA": "S_Serine",
    "TCG": "S_Serine",
    "AGT": "S_Serine",
    "AGC": "S_Serine",
    "ACT": "T_Threonine",
    "ACC": "T_Threonine",
    "ACA": "T_Threonine",
    "ACG": "T_Threonine",
    "TGG": "W_Tryptophan",
    "TAT": "Y_Tyrosine",
    "TAC": "Y_Tyrosine",
    "GTT": "V_Valine",
    "GTC": "V_Valine",
    "GTA": "V_Valine",
    "GTG": "V_Valine",
    "TAG": "終始コドン",
    "TGA": "終始コドン",
    "TAA": "終始コドン",
}


codon_table = {
    "A_Alanine": ["GCT", "GCC", "GCA", "GCG"],
    "R_Arginine": ["CGT", "CGC", "CGA", "CGG", "AGA", "AGG"],
    "N_Asparagine": ["AAT", "AAC"],
    "D_Asparticacid": ["GAT", "GAC"],
    "C_Cysteine": ["TGT", "TGC"],
    "Q_Glutamine": ["CAA", "CAG"],
    "E_Glutamicacid": ["GAA", "GAG"],
    "G_Glycine": ["GGT", "GGC", "GGA", "GGG"],
    "H_Histidine": ["CAT", "CAC"],
    "I_Isoleucine": ["ATT", "ATC", "ATA"],
    "L_Leucine": ["TTA", "TTG", "CTT", "CTC", "CTA", "CTG"],
    "K_Lysine": ["AAA", "AAG"],
    "M_Methionine": ["ATG"],
    "F_Phenylalanine": ["TTT", "TTC"],
    "P_Proline": ["CCT", "CCC", "CCA", "CCG"],
    "S_Serine": ["TCT", "TCC", "TCA", "TCG", "AGT", "AGC"],
    "T_Threonine": ["ACT", "ACC", "ACA", "ACG"],
    "W_Tryptophan": ["TGG"],
    "Y_Tyrosine": ["TAT", "TAC"],
    "V_Valine": ["GTT", "GTC", "GTA", "GTG"],
    "開始コドン": ["ATG"],
    "終始コドン": ["TAG", "TGA", "TAA"],
}
